### ISSUE TITLE
Hide google-services.json

### ISSUE THREAD

**Issue by aminecmi** [dacsi/shows2#1]
@fermatijoe 
This file seems to be containing api keys.

You may want to create another firebase project, and also add the google-services.json file to your .gitignore

**Comment by fermatijoe** [comment]
Working on it. Thanks.

**Comment by fermatijoe** [comment]
Hello I have trouble hiding the API KEY. When I built the app to launch it some illegal characters appear in BuildConfig.java. Here you can see:

http://i.imgur.com/ThtIMbC.png

here is what I wrote in the gradle.proeprties file:

`TMDB_API_KEY = “480a9e79c0937c9f4e4a129fd0463f961”`

(this is still the old API KEY, as soon as I get this working I'll request a new one).
Thanks.

**Comment by aminecmi** [comment]
@fermatijoe change `“` and `”` by the quote symbol.

**Comment by fermatijoe** [comment]
Thanks didn't notice they were different. I redacted everything and will delete the commit history now.
