### ISSUE TITLE
Missing license file

### ISSUE THREAD

**Issue by walrus543** [dacsi/shows2#12]
Hi,
Could you please add license file to know how you publish your app?
Thank you.

**Comment by fermatijoe** [comment]
Hello, I will do this soon. As of today you may build the apk and only use it yourself, please use the play store link when distributing to others.

**Comment by walrus543** [comment]
OK, thank you. It was to suggest your app to F-Droid but I've just seen that you are using firebase.

**Comment by fermatijoe** [comment]
Thank you, have a good day.
