### ISSUE TITLE
Untranslated hardcoded strings

### ISSUE THREAD

**Issue by octarino** [dacsi/shows2#5]
Categories in the drawer
here: [nav_header_main.xml#L25](https://github.com/fermatijoe/shows2/blob/d2a0a86f766ec2c1a189b0db10b9bbab5ee159db/app/src/main/res/layout/nav_header_main.xml#L25)

About in the drawer
here: [menu_navigation_drawer_bottom.xml#L7](https://github.com/fermatijoe/shows2/blob/d2a0a86f766ec2c1a189b0db10b9bbab5ee159db/app/src/main/res/menu/menu_navigation_drawer_bottom.xml#L7)

The about dialog
here: [MainActivity.java#L156](https://github.com/fermatijoe/shows2/blob/b98112db72a13641963279dcd4f9f10ece3db2e4/app/src/main/java/com/dcs/shows/MainActivity.java#L156)

Release date
here: [fragment_detail.xml#L133](https://github.com/fermatijoe/shows2/blob/7f2fe3d0ee0353d3f99ec4c81421612bea281454/app/src/main/res/layout/fragment_detail.xml#L133)

Vote average
here: [fragment_detail.xml#L161](https://github.com/fermatijoe/shows2/blob/7f2fe3d0ee0353d3f99ec4c81421612bea281454/app/src/main/res/layout/fragment_detail.xml#L161)

Similar shows
here: [fragment_detail.xml#L334](https://github.com/fermatijoe/shows2/blob/7f2fe3d0ee0353d3f99ec4c81421612bea281454/app/src/main/res/layout/fragment_detail.xml#L334)

Advanced search
here: [activity_main_drawer.xml#L35](https://github.com/fermatijoe/shows2/blob/b98112db72a13641963279dcd4f9f10ece3db2e4/app/src/main/res/menu/activity_main_drawer.xml#L35)

movie/TV search
here: [fragment_advanced_movie.xml#L32](https://github.com/fermatijoe/shows2/blob/7f2fe3d0ee0353d3f99ec4c81421612bea281454/app/src/main/res/layout/fragment_advanced_movie.xml#L32)

Search
here: [activity_search.xml#L8](https://github.com/fermatijoe/shows2/blob/d2a0a86f766ec2c1a189b0db10b9bbab5ee159db/app/src/main/res/menu/activity_search.xml#L8)

**Comment by fermatijoe** [comment]
I will do them ASAP.

**Comment by octarino** [comment]
When you have them let me know through reddit and I'll translate them.

**Comment by fermatijoe** [comment]
I committed the changes.

**Comment by octarino** [comment]
I made the translations.

Here is other hardcoded strings: 

"No internet connection"[ListFragment.java#L120](https://github.com/fermatijoe/shows2/blob/87427ce5a3396147412bd1dfb079f2ea33240420/app/src/main/java/com/dcs/shows/ListFragment.java#L120) and here: [AdvancedPersonFragment.java#L78](https://github.com/fermatijoe/shows2/blob/7f2fe3d0ee0353d3f99ec4c81421612bea281454/app/src/main/java/com/dcs/shows/AdvancedPersonFragment.java#L78)

"About this app" [MainActivity.java#L143](https://github.com/fermatijoe/shows2/blob/87427ce5a3396147412bd1dfb079f2ea33240420/app/src/main/java/com/dcs/shows/MainActivity.java#L143)

**Comment by fermatijoe** [comment]
Yep thanks.
