### ISSUE TITLE
[enhancement] Screenshots for the Spanish version of Google Play

### ISSUE THREAD

**Issue by octarino** [dacsi/shows2#8]
![screenshot_20161024-163950](https://cloud.githubusercontent.com/assets/22935424/19653437/743a0680-9a0c-11e6-97e6-368c42e0a7aa.png)

Navega un inmenso catálogo de películas

---

![screenshot_20161024-164434](https://cloud.githubusercontent.com/assets/22935424/19653459/90f9cb98-9a0c-11e6-9315-233f33228c7f.png)

Mira las descripciones, puntuaciones y trailers

---

![screenshot_20161024-165120](https://cloud.githubusercontent.com/assets/22935424/19653560/e6ca0542-9a0c-11e6-8050-500b35131f31.png)

Guarda tus películas y series favoritas

---

![screenshot_20161024-165202](https://cloud.githubusercontent.com/assets/22935424/19653590/feecd49c-9a0c-11e6-8950-a1405852a663.png)

Descubre películas y series al azar

**Comment by fermatijoe** [comment]
Thanks a lot. They are added.
